# only needed if using groovy scripting, to avoid Spring template warning
spring:
  groovy:
    template:
      check-template-location: false

server:
  port: 8585 #Port for webserver to run (/health endpoint can be used to monitor service is up)

logging:
  file:
    name: cx-engines.log
  level:
    com:
      checkmarx:
        engine: INFO
    org:
      apache:
        http: INFO
      springframework: INFO

cx:
  cxEngineUseSSL: false #Use http/https to monitor and register Engines with
  concurrentScanLimit: 3 #Max number of concurrent scans (Engines) that DE will manage
  cxEnginePrefix: '**' #Prefix used within Registering engine in CX UI
  expireEngineBufferMins: 1 #Grace period before expiring and engine
  idleMonitorSecs: 30 #How often to check idle engines to determine if expired (ready for termination)
  queueCapacity: 100
  queueIntervalSecs: 15
  queueingEngineName: DynamicEngine #Name given to the Blocked Engine in Cx UI
  restUrl: https://xxxx.com
  timeoutSecs: 120 #HTTP client request timeout (connection and read)
  terminateOnStop: false
  userName: xxx #Checkmarx user (must have access to register engines)
  password: xxx #Checkmarx password

cx-aws-engine:
  assignPublicIP: true
  cxEngineTimeoutSec: 600 #how many seconds to wait for instance to launch before considered a failure
  cxVersion: 8.9.0-HF1
#  engineSizeMap:
#    S: t3.large
#    M: m5.xlarge
#    L: r5.xlarge
#    XL: r5.2xlarge
  iamProfile: cx-de
  imageId: ami-04e7c91826d179728 #AMI ID of the Engine Server
  keyName: Cx_DE #AWS Key name for support purposes
  launchTimeoutSec: 60 #Amount of time to wait for an instance to move out of PENDING state in AWS
  monitorPollingIntervalSecs: 10 #Number of seconds before checking both Instance state and checking if the the HTTP endpoint is available on the Engine
#  scriptOnLaunch: scripts/launch.groovy
#  scriptOnTerminate: scripts/terminate.groovy
  securityGroup: sg-04ed28298b8ec3106 #AWS Security Group to apply to launched Engines
  stopWaitTimeSecs: 30    #time to wait for a stopping engine before attempting to start 
  subnetId: subnet-39b72265 #AWS Subnet ID to launch Engines into
#  tagMap:
#    client: abc
#    component: dynamic-engine
  usePublicUrlForCx: false #Cx will register the Engine with Public or Private IP
  usePublicUrlForMonitor: false #DE will monitor if an Engine is up and running based on Public or Private IP

cx-azure-engine:
  client-id: XXXX #Service Principal client id
  secret: XXXX #Service Principal secret
  tenant-id: XXXX #Azure tenant / domain id
  assignPublicIP: false
  cxEngineTimeoutSec: 600         #how many seconds to wait for instance to launch before considered a failure
  cxVersion: 8.9.0-HF1
#  engineSizeMap: #Azure Instance size mapping
#    S: Standard_B2s
#    M: Standard_B2ms
#    L: Standard_DS2_v2
  launchTimeoutSec: 60            #Amount of time to wait for an instance to move out of PENDING state in AWS
  monitorPollingIntervalSecs: 10  #Number of seconds before checking both Instance state and checking if the the HTTP endpoint is available on the Engine
# scriptOnLaunch: scripts/launch.groovy
# scriptOnTerminate: scripts/terminate.groovy
#  tagMap: #Tags that will be applied to instance (used to listing/tracking available engines)
#    Component: cx-de
#    Owner: abc
  usePublicUrlForCx: false        #Cx will register the Engine with Public or Private IP
  usePublicUrlForMonitor: false    #DE will monitor if an Engine is up and running based on Public or Private IP
  image-name: DE #Name of the CxEngine Image that will be used
  network-name: DE #Azure Network name to launch VMs into
  subnet-name: DE #Subnet name to launch VMs into
  region: eastus #Azure Region
  resource-group: DE-resources #Azure Resource group
  server-admin: cxengine #Default Administrator user
  server-password: XXXX #Default Administrator password

cx-engine:
  engineExpireIntervalSecs: 3600 #Blocks of time an instance is paid by - this is used for expiring/termination of instances
  enginePrefix: cx-engine #Prefix given to naming the instance within the cloud provider
  pool:
    - count: 3 #Maximum number of instances that will be launched for this pool mapping
      minimum: 0 #Leave as zero to ensure engines are cleaned up, otherwise engines will stay at a minimum count once one is launched
      scanSize:
        maxLOC: 250000
        minLOC: 100000
        name: S #Name to map to the cx-aws-engine.engineSizeMap
    - count: 3
      minimum: 0
      scanSize:
        maxLOC: 1000000
        minLOC: 250000
        name: M
    - count: 1
      minimum: 0
      scanSize:
        maxLOC: 2500000
        minLOC: 1000000
        name: L
    - count: 1
      minimum: 0
      scanSize:
        maxLOC: 999999999
        minLOC: 2500000
        name: XL
        